### PR TITLE
Allow using a markdown parser on the examples captions (surrounded by…

### PR DESCRIPTION
**Pull request by vbardales**
… useless HTML p tags)

### CODE REVIEW

**Comment by lukeapage** [comment]
Thanks, Will take a look soon, just short on time.

**Comment by lukeapage** [comment]
Thanks @vbardales - how do I get markdown in my caption in jsdoc to compile?

**Comment by vbardales** [comment]
In your jsdocConfig.json, 

```json
  "markdown": {
    "tags": ["examples"]
  },
```

**Comment by lukeapage** [comment]
I've published this, but I cannot get it to work - when I switch on markdown parsing of examples, everything in the example tag gets parsed, meaning my code gets br tags in it..
Is there something I'm missing?
You can see my test in the commit above (I removed the config for now, but obviously tested with `"tags": ["examples"]`

**Comment by vbardales** [comment]
Here is an example of @example tag I'm using: 
```js
  /**
   * @summary Returns an Hello World
   * @example
   * <caption>Simple function declaration</caption>
   * function restApiResource() {
   *   return 'helloWorld';
   * }
   */
```

and it works fine

**Pull request merged**
